require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PastorsController do

  # This should return the minimal set of attributes required to create a valid
  # Pastor. As you add validations to Pastor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PastorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pastors as @pastors" do
      pastor = Pastor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pastors).should eq([pastor])
    end
  end

  describe "GET show" do
    it "assigns the requested pastor as @pastor" do
      pastor = Pastor.create! valid_attributes
      get :show, {:id => pastor.to_param}, valid_session
      assigns(:pastor).should eq(pastor)
    end
  end

  describe "GET new" do
    it "assigns a new pastor as @pastor" do
      get :new, {}, valid_session
      assigns(:pastor).should be_a_new(Pastor)
    end
  end

  describe "GET edit" do
    it "assigns the requested pastor as @pastor" do
      pastor = Pastor.create! valid_attributes
      get :edit, {:id => pastor.to_param}, valid_session
      assigns(:pastor).should eq(pastor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pastor" do
        expect {
          post :create, {:pastor => valid_attributes}, valid_session
        }.to change(Pastor, :count).by(1)
      end

      it "assigns a newly created pastor as @pastor" do
        post :create, {:pastor => valid_attributes}, valid_session
        assigns(:pastor).should be_a(Pastor)
        assigns(:pastor).should be_persisted
      end

      it "redirects to the created pastor" do
        post :create, {:pastor => valid_attributes}, valid_session
        response.should redirect_to(Pastor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pastor as @pastor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pastor.any_instance.stub(:save).and_return(false)
        post :create, {:pastor => {}}, valid_session
        assigns(:pastor).should be_a_new(Pastor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pastor.any_instance.stub(:save).and_return(false)
        post :create, {:pastor => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pastor" do
        pastor = Pastor.create! valid_attributes
        # Assuming there are no other pastors in the database, this
        # specifies that the Pastor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pastor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => pastor.to_param, :pastor => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested pastor as @pastor" do
        pastor = Pastor.create! valid_attributes
        put :update, {:id => pastor.to_param, :pastor => valid_attributes}, valid_session
        assigns(:pastor).should eq(pastor)
      end

      it "redirects to the pastor" do
        pastor = Pastor.create! valid_attributes
        put :update, {:id => pastor.to_param, :pastor => valid_attributes}, valid_session
        response.should redirect_to(pastor)
      end
    end

    describe "with invalid params" do
      it "assigns the pastor as @pastor" do
        pastor = Pastor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pastor.any_instance.stub(:save).and_return(false)
        put :update, {:id => pastor.to_param, :pastor => {}}, valid_session
        assigns(:pastor).should eq(pastor)
      end

      it "re-renders the 'edit' template" do
        pastor = Pastor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pastor.any_instance.stub(:save).and_return(false)
        put :update, {:id => pastor.to_param, :pastor => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pastor" do
      pastor = Pastor.create! valid_attributes
      expect {
        delete :destroy, {:id => pastor.to_param}, valid_session
      }.to change(Pastor, :count).by(-1)
    end

    it "redirects to the pastors list" do
      pastor = Pastor.create! valid_attributes
      delete :destroy, {:id => pastor.to_param}, valid_session
      response.should redirect_to(pastors_url)
    end
  end

end
